../src/dmem.v
../src/dmem_wrab.v
../src/ex_stage.v
../src/forwarding.v
../src/id_stage.v
../src/if_stage.v
../src/imem.v
../src/mem_stage.v
../src/registers_file.v
../src/top_system.v
../src/uart_tx.v
../src/uart_rx.v
../src/i2c_slave.v
../src/i2c_master.v
