../src/defines.vh
../src/dmem.v
../src/dmem_wrab.v
../src/ex_stage.v
../src/forwarding.v
../src/i2c_master.v
../src/i2c_slave.v
../src/id_stage.v
../src/if_stage.v
../src/imem.v
../src/load_cvt.v
../src/mem_stage.v
../src/registers_file.v
../src/store_cvt.v
../src/top_rv32.v
#../src/top_system.v
../src/uart_rx.v
../src/uart_tx.v